puts "The students of Villains Academmy"
puts "--------------"
puts "Dr. Hannibal Lechter"
puts "Darth Vader"
puts "Nurse Rathed"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "The Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"